# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e9dadf5a4957a399c825121e2676d66b7f006149478a6202386a133ba13cb371807e9929bf44bc5f536e9cdd0bac83840965662ea0849926627350c811e2be9

test:
  secret_key_base: d012734acd220673e943c653a61363c4551ee18f74e91a9951253c519efb800bd7814d5fc6e7f4b5c94d019d389452592b6011e5f3e242aa1d3d6c70e24036a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
